### ISSUE TITLE
Optional Parameter for Seed

### ISSUE THREAD

**Issue by Lux-Ferre** [duchesneaumathieu/pyperlin#1]
Enhancement request to be able to use a seed for noise generation.

It might be possible by just using the manual_seed(_seed_) method of the torch generator object.

**Comment by duchesneaumathieu** [comment]
It is possible using the manual_seed method of the generator object. E.g.,
```python
shape = (1,1024,1024) #for batch size = 1 and noises' shape = (1024,1024)
factors = [.5**i for i in range(8)] #for persistence = 0.5
g_cuda = torch.Generator(device='cuda') #for GPU acceleration
g_cuda.manual_seed(0xcafe) #<--- by adding this line

clouds_resolutions = [(2**i,2**i) for i in range(1,7)] #for lacunarity = 2.0
clouds_factors = [.5**i for i in range(6)] #for persistence = 0.5
clouds = FractalPerlin2D(shape, clouds_resolutions, clouds_factors, generator=g_cuda)().cpu().numpy()[0]
```
That way, the clouds will always be the same. Is this what you were asking for?

**Comment by Lux-Ferre** [comment]
I was finally able to test this and it did exactly what I needed. I feel a little silly for not recognising that I could do that without passing a new parameter into FractalPerlin2D. Thank-you.

**Comment by duchesneaumathieu** [comment]
No problems, I'm happy to see that this code is useful for someone! 👍
